### ISSUE TITLE
Should document.domain setter be considered different than 'self' ?

### ISSUE THREAD

**Issue by bakulf** [w3c/webappsec-feature-policy#253]
Let's say that a page receives `Feature-Policy: fullscreen 'self'`. If then the page does: `document.domain = something`, should we allow fullscreen or not? By spec yes, because:

https://wicg.github.io/feature-policy/#parse-policy-directive
9.3.2.9.3.1 "If element is an ASCII case-insensitive match for "'self'", let result be container origin. "

Is this the expected behavior? Should we copy/clone the origin instead? If we copy/clone the origin, 'self' features will not be granted after setting document.domain.

@clelland, would be nice if the spec clarifies this aspect. A note should be sufficient.

**Comment by clelland** [comment]
The document's policy is set before any scripts can run, and doesn't change after that point, so fullscreen should be allowed both before and after setting `document.domain`.

I think this falls out of the fact that [Initialize document’s Feature Policy from response](https://wicg.github.io/feature-policy/#initialize-from-response) is called as part of initializing the document object. There is an example at https://html.spec.whatwg.org/multipage/browsing-the-web.html#initialise-the-document-object which covers just this (though using PaymentRequest rather than requestFullscreen)

**Comment by annevk** [comment]
> At the time the child document is initialized, none of the documents have set document.domain yet so same origin-domain falls back to a normal same origin check.

So if you set `document.domain` and then create an `<iframe>` it would not be a match?

**Comment by bzbarsky** [comment]
> The document's policy is set before any scripts can run

While true, the document's policy is a list of origins right now, not a list of booleans, right?

Setting document.domain mutates the document's origin.  One question is whether the origin stored in the policy is an alias or a copy.  If it's a copy, it would stop matching and the next policy check would fail.

If it's an alias, then fullscreen would continue to be allowed, sure, and would also be allowed in the case @annevk mentions.

But then why is the check doing "same origin-domain" checks at all?  What is the point of those?

**Comment by clelland** [comment]
I think that the original reasoning was to preserve the behavior in https://github.com/whatwg/html/commit/ffae69861afaff9ca1c1f058f1d7af95412f60fa for PaymentRequest, and it seemed like it was slightly stricter in practice, and most of the time wouldn't make a difference. That said, I realize the issue you're talking about now: setting domain could lock yourself out of features you previously had access to, which is definitely not a goal. (Ideally, the set of features a document will be granted is fixed when the document is created.) 

Chrome's implementaion right now uses a same-origin check, without regard to domain. Maybe we should codify that, rather than trying to make the same-origin-domain check make sense in all cases.

**Comment by annevk** [comment]
Even with a strict same-origin check there's still the question of whether 'self' matches an opaque origin. This does not matter for CSP, but does for FP.

I looked into the history of using same origin-domain for all of this and it turns out that we never added tests for that: https://github.com/web-platform-tests/wpt/issues/4526. Shows what happens when we're sloppy with that.

@zcorpan I suppose you don't feel too strongly if we make this less strict and don't use same origin-domain for these checks?

**Comment by zcorpan** [comment]
Nope, we can change that.

**Comment by clelland** [comment]
I changed the spec to use same-origin checks.

Re: https://github.com/w3c/webappsec-feature-policy/issues/253#issuecomment-486219420, it should match an opaque origin. If a document is loaded into a sandbox, and is served with a `Feature-Policy` header which references `'self'`, then that should refer to the document's origin.

If `'self'` is used in an `allow` attribute where the nested document is sandboxed, then that should *never* match, since `'self'` in that case refers to the origin of the document containing the `<iframe>` tag, which can never be same-origin with sandboxed content (modulo `allow-same-origin`)

(And opaque origins are comparable, and an opaque origin is same-origin with itself, according to [\[URL\]](https://html.spec.whatwg.org/multipage/origin.html#same-origin). I think that's covered.
