### ISSUE TITLE
Broken link in the repo's description

### ISSUE THREAD

**Issue by dandv** [w3c/webappsec-feature-policy#265]
The https://wicg.github.io/feature-policy/ is broken

![image](https://user-images.githubusercontent.com/33569/50315554-195ac600-0468-11e9-8b31-e8eed2e36272.png)

**Comment by clelland** [comment]
We're halfway through the process of migrating this to w3c; the eventual location will be https://w3c.github.io/webappsec-feature-policy, and as soon as we get there I'll try to update everything.

Unfortunately, it doesn't seem like github lets you rename and transfer in one action.

**Comment by wseltzer** [comment]
https://github.com/w3c/webappsec-feature-policy/pull/266

**Comment by clelland** [comment]
Thanks, @wseltzer - closing this.

**Comment by annevk** [comment]
I would have appreciated a bit more diligence and redirecting the old link as well. The HTML Standard had broken links to Feature Policy for 13 days. Not a big deal due to the holidays probably, but still.

Also, all the old issue links are still broken, leaving folks trying to determine rationale at some point in the future with a mess.
