### ISSUE TITLE
The value of report.type doesn't match docs

### ISSUE THREAD

**Issue by ScottHelme** [w3c/webappsec-feature-policy#267]
Looking at the Chrome test cases for FP Reporting I see the following:

```
var check_report_format = (reports, observer) => {
 let report = reports[0];
 assert_equals(report.type, "feature-policy");
```

In `reporting.md` the `report.type` is listed as `feature-policy-violation`:

https://github.com/w3c/webappsec-feature-policy/blame/master/reporting.md#L42

**Comment by clelland** [comment]
`feature-policy-violation` should be the correct type. Between commits [a061ddee96275](https://crrev.com/a061ddee96275) and [aa5ddc8f58d3c](https://crrev.com/aa5ddc8f58d3c), those should all have been changed in the Web Platform Tests, which Chrome uses.

If you've found a case that was missed, let me know where and I'll get it fixed in Chrome right away. (Although it should be causing test failures which we'd see, it's possible that they're being silenced for some reason)

**Comment by ScottHelme** [comment]
Ah yes, my lack of familiarity with the code, looks good!
