### ISSUE TITLE
Dividing features across different types of policies

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-feature-policy#296]
As per https://github.com/w3c/webappsec-feature-policy/issues/282#issuecomment-486267212 the idea is to divide features across different policies. Here's an initial take on that using https://github.com/w3c/webappsec-feature-policy/blob/master/features.md as source:

## Existing features

| Feature name | Delegating permissions | Document sandboxing | Full sandboxing |
| - | - |- | - |
| `accelerometer` | ✓ | | |
| `ambient-light-sensor` | ✓ | | |
| `autoplay` | ? | | |
| `camera` | ✓ | | |
| `document-domain` | | ? (I think this is a new primitive and I'm not convinced it's worth it) | ✓ |
| `fullscreen` | ✓ | | |
| `gyroscope` | ✓ | | |
| `magnetometer` | ✓ | | |
| `microphone` | ✓ | | |
| `midi` | ✓ | | |
| `picture-in-picture` | ✓ | | |
| `sync-xhr` | | ✓ | ✓ |
| `usb` | ✓ | | |
| `wake-lock` | ✓ | | |
| `xr` | ✓ | | |

## Proposed features

| Feature name | Delegating permissions | Document sandboxing | Full sandboxing |
| - | - |- | - |
| Client Hints | | | | 
| `encrypted-media` | ? | | |
| `geolocation` | ✓ | | |
| `payment` | ✓ | | |
| `speaker` | ✓ | | |

## Experimental features

| Feature name | Delegating permissions | Document sandboxing | Full sandboxing |
| - | - |- | - |
| `document-write` | | ✓ | ✓ |
| `font-display-late-swap` | | ✓ | ✓ |
| `layout-animations` | | ✓ | ✓ |
| `lazyload` | | ✓ | ✓ |
| `legacy-image-formats` | | ✓ | ✓ |
| `oversized-images` | | ✓ | ✓ |
| `sync-script` | | ✓ | ✓ |
| `unoptimized-images` | | ✓ | ✓ |
| `unsized-media` | | ✓ | ✓ |
| `vertical-scroll` | | ✓ | ✓ |
| `serial` | | |  |

(I'm not entirely sure about all of these, let's try to keep this comment updated as we reach firmer conclusions on each of them.)

**Comment by Malvoz** [comment]
There are PR's to split the current `lazyload` feature into 2 features:
[`loading-image-default-eager`](https://github.com/w3c/webappsec-feature-policy/pull/295) and [`loading-frame-default-eager`](https://github.com/w3c/webappsec-feature-policy/pull/297)

**Comment by eeeps** [comment]
Will these different feature-types will be getting different:

- Syntaxes for values? (seems likely)
- Header/attribute names? (not sure)
- Specs? (seems less likely)

**Comment by clelland** [comment]
The most compelling insight from this table, I think, is that delegation and sandboxing are two different domains, and that if we're looking at splitting FP into different mechanisms, that seems like a clear distinction that we can make.

Delegation matches the existing spec quite well, and if we were to focus it on just that use case, we could probably trim it down a bit, too.

I'm just working on an actual proposal, but I would suggest:
 - Different syntaxes, due to the deployment of existing delegation
 - Different header / attribute names for the two kinds of features.
 - One spec or two? Hard to say what's better; keeping everything here is administratively easier, certainly.

**Comment by clelland** [comment]
Closing with the introduction of Document Policy; the document/full sandboxing features listed in the initial description are all movable to that mechanism (I'll open a separate issue for SyncXHR)
